/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SIDAM
 */
public class mainFrame extends javax.swing.JFrame {
    private pCRUD jurusan = new pCRUD();
    private pBeli mahasiswa = new pBeli();
    /**
     * Creates new form mainFrame
     */
    public mainFrame() throws ClassNotFoundException {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        setTitle("tutorial Layout");
        
        panelForm.add(jurusan,"pJurusan");
        panelForm.add(mahasiswa,"pMahasiswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bDasboard = new javax.swing.JButton();
        bTampil = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        panelForm = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bDasboard.setText("Dasboard");
        bDasboard.setFocusable(false);
        bDasboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDasboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDasboardActionPerformed(evt);
            }
        });
        jToolBar1.add(bDasboard);

        bTampil.setText("Kasir");
        bTampil.setFocusable(false);
        bTampil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bTampil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTampilActionPerformed(evt);
            }
        });
        jToolBar1.add(bTampil);

        bJurusan.setText("Data Obat");
        bJurusan.setFocusable(false);
        bJurusan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bJurusan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJurusanActionPerformed(evt);
            }
        });
        jToolBar1.add(bJurusan);

        bLogin.setText("Login");
        bLogin.setFocusable(false);
        bLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(bLogin);

        bLogout.setText("Logout");
        bLogout.setFocusable(false);
        bLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(bLogout);

        panelForm.setLayout(new java.awt.CardLayout());

        jLabel1.setText("dasboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        panelForm.add(dashboard, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void bTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTampilActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "pMahasiswa");
    }//GEN-LAST:event_bTampilActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        String inputan = JOptionPane.showInputDialog("Inputkan Sesuatu");
    JOptionPane.showMessageDialog(this, "Kamu meng-inputkan: " + inputan);
        
    }//GEN-LAST:event_bLoginActionPerformed

    private void bDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDasboardActionPerformed
        // TODO add your handling code here:
       mahasiswa.setVisible(false);
    jurusan.setVisible(false);
        panelForm.setVisible(true);
    }//GEN-LAST:event_bDasboardActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "pJurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
                    new mainFrame().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDasboard;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bTampil;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
