/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SIDAM
 */
public class mainFrame extends javax.swing.JFrame {
    boolean login_status=false;
    private pCRUD crud = new pCRUD();
    private pJual beli = new pJual();
    private pStok stok = new pStok();
    private pTransaksi transaksi = new pTransaksi();

    /**
     * Creates new form mainFrame
     */
    public mainFrame() throws ClassNotFoundException {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        setSize(900,600);
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        
        this.setLocation(x, y);
        setTitle("tutorial Layout");
        
        panelForm.add(crud,"pcrud");
        panelForm.add(beli,"pbeli");
        panelForm.add(transaksi,"ptransaksi");
        panelForm.add(stok,"pstok");
        belumLogin();
    }
    
    private void belumLogin(){
        login_status=false;
            bBeli.setEnabled(false);
            bLogin.setEnabled(true);
            bLogout.setVisible(false);
            bTransaksi.setEnabled(false);
            bStok.setEnabled(false);
            bCRUD.setEnabled(false);
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bDasboard = new javax.swing.JButton();
        bBeli = new javax.swing.JButton();
        bStok = new javax.swing.JButton();
        bTransaksi = new javax.swing.JButton();
        bCRUD = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        panelForm = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bDasboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDasboard.setText("Dasboard     ");
        bDasboard.setFocusable(false);
        bDasboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDasboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDasboardActionPerformed(evt);
            }
        });
        jToolBar1.add(bDasboard);

        bBeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBeli.setText("Beli     ");
        bBeli.setFocusable(false);
        bBeli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBeli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBeliActionPerformed(evt);
            }
        });
        jToolBar1.add(bBeli);

        bStok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bStok.setText("Stok     ");
        bStok.setFocusable(false);
        bStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bStok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStokActionPerformed(evt);
            }
        });
        jToolBar1.add(bStok);

        bTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bTransaksi.setText("Riwayat     ");
        bTransaksi.setFocusable(false);
        bTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(bTransaksi);

        bCRUD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCRUD.setText("DataObat     ");
        bCRUD.setFocusable(false);
        bCRUD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCRUD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCRUDActionPerformed(evt);
            }
        });
        jToolBar1.add(bCRUD);

        bLogout.setForeground(new java.awt.Color(204, 0, 0));
        bLogout.setText("Logout");
        bLogout.setFocusable(false);
        bLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(bLogout);

        panelForm.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Halaman Login");

        jUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Username");

        bLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jUsername)))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(dashboardLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(119, 119, 119)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panelForm.add(dashboard, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void bBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBeliActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "pbeli");
    }//GEN-LAST:event_bBeliActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Ingin Keluar?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
        
    
    if(jawab == JOptionPane.YES_OPTION){
        belumLogin();
        JOptionPane.showMessageDialog(this, "Berhasil Logout");
        goDasboard();
    }
        
    }//GEN-LAST:event_bLogoutActionPerformed
     private void goDasboard(){
         
     crud.setVisible(false);
        beli.setVisible(false);
        stok.setVisible(false);
        transaksi.setVisible(false);
        panelForm.setVisible(true);
     }
    private void bDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDasboardActionPerformed
        // TODO add your handling code here:
       goDasboard();
    }//GEN-LAST:event_bDasboardActionPerformed

    private void bCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCRUDActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "pcrud");
    }//GEN-LAST:event_bCRUDActionPerformed

    private void bTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransaksiActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "ptransaksi");
    }//GEN-LAST:event_bTransaksiActionPerformed

    private void bStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStokActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)panelForm.getLayout();
        cl.show(panelForm, "pstok");
    }//GEN-LAST:event_bStokActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        
        if("admin".equals(jUsername.getText()) && "admin123".equals(jPassword.getText())){
            login_status=true; 
            bBeli.setEnabled(true);
            bLogin.setEnabled(false);
            bLogout.setVisible(true);
            bTransaksi.setEnabled(true);
            bStok.setEnabled(true);
            bCRUD.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Kamu Berhasil Login");
            CardLayout cl = (CardLayout)panelForm.getLayout();
             cl.show(panelForm, "pbeli");
        }
        else{
            JOptionPane.showMessageDialog(this, "User Pass Tidak Cocok");
        }
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
                    new mainFrame().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBeli;
    private javax.swing.JButton bCRUD;
    private javax.swing.JButton bDasboard;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bStok;
    private javax.swing.JButton bTransaksi;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jUsername;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
