/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SIDAM
 */
public class pJual extends javax.swing.JPanel {
    private static int tharga=0,id,harga,baris;
    private static String nama;
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model1 = new DefaultTableModel();
    /**
     * Creates new form pMahasiswa
     */
   
   
    /**
     * Creates new form panel1
     */
       pJual() throws ClassNotFoundException {
       
        initComponents();
         
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("JUMLAH");
        model.addColumn("HARGA");
         Show_data("select o.id_obat, o.kode, o.nama, o.harga, j.nama_jenis from obat o inner join jenis j on o.jenis=j.id_jenis order by o.id_obat");
        
    }

     private void Show_data(String query) throws ClassNotFoundException{
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("ID");
        model1.addColumn("KODE");
        model1.addColumn("NAMA");
        model1.addColumn("HARGA");
        model1.addColumn("JENIS");
        try{
            int no = 1;
            String sql = query;
            java.sql.Connection db = (Connection) Koneksi.configDB();
            java.sql.Statement stm;
            stm = db.createStatement();
            java.sql.ResultSet result = stm.executeQuery(sql);
            while(result.next()){
                model1.addRow(new Object[]{result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getString(5)});
            }
            tObat.setModel(model1);
        }catch(SQLException e){
            System.out.println("Error : "+e.getMessage());
        }
        
       TableColumn column1;
       tObat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
       column1 = tObat.getColumnModel().getColumn(0);
       column1.setPreferredWidth(30);
        column1 = tObat.getColumnModel().getColumn(1);
       column1.setPreferredWidth(100);
        column1 = tObat.getColumnModel().getColumn(2);
       column1.setPreferredWidth(125);
       column1 = tObat.getColumnModel().getColumn(3);
       column1.setPreferredWidth(100);
        column1 = tObat.getColumnModel().getColumn(4);
       column1.setPreferredWidth(150);
     }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPilihObat = new javax.swing.JTable();
        bHapus = new javax.swing.JButton();
        bSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tNamapembeli = new javax.swing.JTextField();
        lTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tObat = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        tBanyak = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bEmty = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("HALAMAN PEMBELIAN");

        tPilihObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPilihObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPilihObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tPilihObat);

        bHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama Pembeli =");

        tNamapembeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTotal.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total =Rp");

        tObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tObat);

        bTambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bCari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        jLabel3.setText("Banyak =");

        bEmty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bEmty.setText("Emty");
        bEmty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tNamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bTambah)
                            .addComponent(tBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bEmty)
                        .addGap(16, 16, 16)
                        .addComponent(bHapus)
                        .addGap(18, 18, 18)
                        .addComponent(bSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bHapus)
                            .addComponent(bSubmit)
                            .addComponent(lTotal)
                            .addComponent(jLabel4)
                            .addComponent(bEmty)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCari)
                            .addComponent(tBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(bTambah)))
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        tharga=tharga-harga;
         String tot = String.valueOf(tharga);
            lTotal.setText(tot);
        model.removeRow(baris);
        
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed

        int  jumlah = Integer.valueOf(tBanyak.getText());
        
            int hargao = jumlah*harga;
            model.addRow(new Object[]{id, nama, jumlah, hargao});
            tPilihObat.setModel(model);
            tharga=tharga+(hargao);
            String tot = String.valueOf(tharga);
            lTotal.setText(tot);
       TableColumn column;
       tPilihObat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
       column = tPilihObat.getColumnModel().getColumn(0);
       column.setPreferredWidth(30);
        column = tPilihObat.getColumnModel().getColumn(1);
       column.setPreferredWidth(150);
        column = tPilihObat.getColumnModel().getColumn(2);
       column.setPreferredWidth(100);
       column = tPilihObat.getColumnModel().getColumn(3);
       column.setPreferredWidth(100);
            
       
    }//GEN-LAST:event_bTambahActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select o.id_obat, o.kode, o.nama, o.harga, j.nama_jenis from obat o inner join jenis j on o.jenis=j.id_jenis WHERE kode LIKE '%"+tCari.getText()
            +"%'"+"OR nama LIKE '%"+tCari.getText()+"%' order by o.id_obat";
            Show_data(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        tCari.setText(null);
    }//GEN-LAST:event_bCariActionPerformed

    private void tObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tObatMouseClicked
        // TODO add your handling code here:
            int baris = tObat.rowAtPoint(evt.getPoint());
        String sid = tObat.getValueAt(baris, 0).toString();
       id = Integer.valueOf(sid);
       nama = tObat.getValueAt(baris, 2).toString();
       String sha = tObat.getValueAt(baris, 3).toString();
      harga = Integer.valueOf(sha);
    }//GEN-LAST:event_tObatMouseClicked

    private void tPilihObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPilihObatMouseClicked
        // TODO add your handling code here:
        baris = tPilihObat.rowAtPoint(evt.getPoint());
       String sha = tPilihObat.getValueAt(baris, 3).toString();
      harga = Integer.valueOf(sha);
      tNamapembeli.setText(sha);
        
    }//GEN-LAST:event_tPilihObatMouseClicked
    
    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:
        int banyak = model.getRowCount();
        String namap = tNamapembeli.getText();
        Penjualan jual = new Penjualan();
        jual.tambahData(namap, tharga);
        for(int i = 0;i<banyak;i++){
            String io = tPilihObat.getValueAt(i, 0).toString();
            int ido = Integer.valueOf(io);
            String jum =tPilihObat.getValueAt(i, 2).toString();
            int jumlaho = Integer.valueOf(jum);
            String har = tPilihObat.getValueAt(i, 3).toString();
            int hargao = Integer.valueOf(har);
            jual.tambahDetail(ido, jumlaho, hargao);
        }
        
    }//GEN-LAST:event_bSubmitActionPerformed

    private void bEmtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmtyActionPerformed
        // TODO add your handling code here:
        int ba = model.getRowCount();
        for(int i=0;i<ba;i++){
            model.removeRow(0);
        }
        tNamapembeli.setText(null);
        tharga=0;
        lTotal.setText("0");
    }//GEN-LAST:event_bEmtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bEmty;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSubmit;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTextField tBanyak;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tNamapembeli;
    private javax.swing.JTable tObat;
    private javax.swing.JTable tPilihObat;
    // End of variables declaration//GEN-END:variables
}
