/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjava;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SIDAM
 */
public class pTransaksi extends javax.swing.JPanel {
    private int iddetail,total;
    private String nama;
    /**
     * Creates new form pTransaksi
     */
    public pTransaksi() throws ClassNotFoundException {
        initComponents();
        Show_data();
    }
    public void Show_data() throws ClassNotFoundException{
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("TOTAL TRANSAKSI");
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("ID");
        model1.addColumn("NAMA");
        model1.addColumn("TOTAL TRANSAKSI");

        try{
            int no = 1;
            String sql = "select * from transaksi_jual";
            java.sql.Connection db = (Connection) Koneksi.configDB();
            java.sql.Statement stm;
            stm = db.createStatement();
            java.sql.ResultSet result = stm.executeQuery(sql);
            while(result.next()){
                model.addRow(new Object[]{result.getString(1), result.getString(2), result.getString(3)});
            }
            tTransaksi.setModel(model);
        }catch(SQLException e){
            System.out.println("Error : "+e.getMessage());
        }
        
        
        try{
            int no = 1;
            String sql = "select * from transaksi_beli";
            java.sql.Connection db = (Connection) Koneksi.configDB();
            java.sql.Statement stm;
            stm = db.createStatement();
            java.sql.ResultSet result = stm.executeQuery(sql);
            while(result.next()){
                model1.addRow(new Object[]{result.getString(1), result.getString(2), result.getString(3)});
            }
            tTransaksi1.setModel(model1);
        }catch(SQLException e){
            System.out.println("Error : "+e.getMessage());
        }
        
        TableColumn column;
       tTransaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
       column = tTransaksi.getColumnModel().getColumn(0);
       column.setPreferredWidth(50);
        column = tTransaksi.getColumnModel().getColumn(1);
       column.setPreferredWidth(200);
        column = tTransaksi.getColumnModel().getColumn(2);
       column.setPreferredWidth(150);
       TableColumn column1;
       tTransaksi1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
       column1 = tTransaksi1.getColumnModel().getColumn(0);
       column1.setPreferredWidth(50);
        column1 = tTransaksi1.getColumnModel().getColumn(1);
       column1.setPreferredWidth(200);
        column1 = tTransaksi1.getColumnModel().getColumn(2);
       column1.setPreferredWidth(150);
       
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTransaksi = new javax.swing.JTable();
        bDetail = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTransaksi1 = new javax.swing.JTable();
        bDetail1 = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RIWAYAT TRANSAKSI PENJUALAN");

        tTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tTransaksi);

        bDetail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDetail.setText("Lihat Detail");
        bDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetailActionPerformed(evt);
            }
        });

        tTransaksi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tTransaksi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTransaksi1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tTransaksi1);

        bDetail1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bDetail1.setText("Lihat Detail");
        bDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetail1ActionPerformed(evt);
            }
        });

        bRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Riwayat Penjualan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Riwayat Penyetokan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(bDetail))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(bDetail1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(bRefresh)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDetail)
                    .addComponent(bDetail1))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tTransaksi.rowAtPoint(evt.getPoint());
        
        String sid = tTransaksi.getValueAt(baris, 0).toString();
        iddetail=Integer.valueOf(sid);
        nama = tTransaksi.getValueAt(baris, 1).toString();
        String tot = tTransaksi.getValueAt(baris, 2).toString();
        total=Integer.valueOf(tot);
    }//GEN-LAST:event_tTransaksiMouseClicked

    private void bDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetailActionPerformed
        try {
            // TODO add your handling code here:
            new fTransaksiDetail(iddetail,total,nama,1).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDetailActionPerformed

    private void bDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetail1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            new fTransaksiDetail(iddetail,total,nama,2).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDetail1ActionPerformed

    private void tTransaksi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTransaksi1MouseClicked
        // TODO add your handling code here:
        int baris = tTransaksi1.rowAtPoint(evt.getPoint());
        
        String sid = tTransaksi1.getValueAt(baris, 0).toString();
        iddetail=Integer.valueOf(sid);
        nama = tTransaksi1.getValueAt(baris, 1).toString();
        String tot = tTransaksi1.getValueAt(baris, 2).toString();
        total=Integer.valueOf(tot);
    }//GEN-LAST:event_tTransaksi1MouseClicked

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        try {
            // TODO add your handling code here:
            Show_data();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(pTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDetail;
    private javax.swing.JButton bDetail1;
    private javax.swing.JButton bRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tTransaksi;
    private javax.swing.JTable tTransaksi1;
    // End of variables declaration//GEN-END:variables
}
